main: main.cpp persona.cpp generapersona.cpp generapersona.hpp edi_LinkedList.hpp edi_List.hpp edi_export.hpp asignatura.hpp
	g++ -g -Wall main.cpp persona.cpp generapersona.cpp -o main

clean:
	rm main