;Ejercicio del factorial
;Lo tenemos que hacer con 3 reglas para poder capturar el factorial y hacernos con todos :>

;Esto es para el ejercicio anterior (/ (+ ?x ?y) 2)
;Para la mediana hay que ponerle eso a los numeros pares

(defrule factorial
	;Aqui hacemos el factorial :>

)

(defrule pedirdatos
	;Aqui le pedimos los datos al usuario
)

(defrule algomas
	;Esta es la tercera regla que hay que hacer pero no se para que sirve :>
)


(defrule do||do not there's no try
)