/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rotationbutton;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import javax.swing.ImageIcon;
import java.beans.*;

/**
 *
 * @author jopepato
 */
public class RotationButton extends javax.swing.JPanel {

    /**
     * Creates new form RotationButton
     */
    
    ImageIcon icon0;
    ImageIcon icon1;
    ImageIcon icon2;
    ImageIcon icon3;
    ImageIcon icon4;
    ImageIcon icon5;
    ImageIcon icon6;
    ImageIcon icon7;
    ImageIcon icon8;
    ImageIcon icon;
    ImageIcon icon32;
    ImageIcon iconM;
    ImageIcon icon32M;
    public RotationButton() {
        initComponents();
        setPosicion(0);
        
        icon0 = new ImageIcon(getClass().getResource("/images/boton0.jpg"));
        icon1 = new ImageIcon(getClass().getResource("/images/boton1.jpg"));   
        icon2 = new ImageIcon(getClass().getResource("/images/boton2.jpg"));
        icon3 = new ImageIcon(getClass().getResource("/images/boton3.jpg"));
        icon4 = new ImageIcon(getClass().getResource("/images/boton4.jpg"));
        icon5 = new ImageIcon(getClass().getResource("/images/boton5.jpg"));        
        icon6 = new ImageIcon(getClass().getResource("/images/boton6.jpg"));
        icon7 = new ImageIcon(getClass().getResource("/images/boton7.jpg"));
        icon8 = new ImageIcon(getClass().getResource("/images/boton8.jpg"));

        
        icon = new ImageIcon(getClass().getResource("/icon/jp16c.gif"));
        icon32 = new ImageIcon(getClass().getResource("/icon/jp32c.gif"));
        iconM = new ImageIcon(getClass().getResource("/icon/jp16m.gif"));
        icon32M = new ImageIcon(getClass().getResource("/icon/jp32m.gif"));
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        jButtonDown = new javax.swing.JButton();
        jButtonUp = new javax.swing.JButton();

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton0.jpg"))); // NOI18N

        jButtonDown.setBackground(new java.awt.Color(153, 255, 51));
        jButtonDown.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDown.setText("-");
        jButtonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownActionPerformed(evt);
            }
        });

        jButtonUp.setBackground(new java.awt.Color(255, 102, 102));
        jButtonUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUp.setText("+");
        jButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(image)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButtonDown)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonUp)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDown)
                    .addComponent(jButtonUp)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public ImageIcon getIcon(int i){
        switch(i)
        {
        case 1:
             return icon;
 
        case 2:
            return icon32;
 
        case 3:
            return iconM;
 
        case 4:
            return icon32M;
        }
         return null;
     }
    
    
    private void jButtonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownActionPerformed
        // TODO add your handling code here:
        if(getPosicion()>0 && getPosicion() <=8){
            setPosicion(getPosicion()-1);
        }
        //Llamamos funcion
        cambiaIcono(getPosicion());
    }//GEN-LAST:event_jButtonDownActionPerformed

    private void jButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpActionPerformed
        // TODO add your handling code here:
        if(getPosicion()>=0 && getPosicion()<8){
            setPosicion(getPosicion() +1 );
        }
        //Llamamos funcion
        cambiaIcono(getPosicion());
    }//GEN-LAST:event_jButtonUpActionPerformed

    private void cambiaIcono(int posicion){
        switch(posicion){
            case 0:
                image.setIcon(icon0);
                break;
            case 1:
                image.setIcon(icon1);
                break;
            case 2:
                image.setIcon(icon2);
                break;
            case 3:
                image.setIcon(icon3);
                break;
            case 4:
                image.setIcon(icon4);
                break;
            case 5:
                image.setIcon(icon5);
                break;
            case 6:
                image.setIcon(icon6);
                break;
            case 7:
                image.setIcon(icon7);
                break;
            case 8:
                image.setIcon(icon8);
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JButton jButtonDown;
    private javax.swing.JButton jButtonUp;
    // End of variables declaration//GEN-END:variables
    private int posicion;

    public int getPosicion() {
        return posicion;
    }

    public void setPosicion(int posicion) {
        this.posicion = posicion;
    }
    
    
}
