/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wheel;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author i32petoj
 */
public class wheelFrame extends javax.swing.JFrame {

    /**
     * Creates new form wheelFrame
     */
        ImageIcon icon0;
        ImageIcon icon1;
        ImageIcon icon2;
        ImageIcon icon3;
        ImageIcon icon4;
        ImageIcon icon5;
        ImageIcon icon6;
        ImageIcon icon7;
        ImageIcon icon8;
    public wheelFrame() {
        initComponents();
        setPosicion(0);
        
        icon0 = new ImageIcon(getClass().getResource("/icon/boton0.jpg"));
        icon1 = new ImageIcon(getClass().getResource("/icon/boton1.jpg"));   
        icon2 = new ImageIcon(getClass().getResource("/icon/boton2.jpg"));
        icon3 = new ImageIcon(getClass().getResource("/icon/boton3.jpg"));
        icon4 = new ImageIcon(getClass().getResource("/icon/boton4.jpg"));
        icon5 = new ImageIcon(getClass().getResource("/icon/boton5.jpg"));        
        icon6 = new ImageIcon(getClass().getResource("/icon/boton6.jpg"));
        icon7 = new ImageIcon(getClass().getResource("/icon/boton7.jpg"));
        icon8 = new ImageIcon(getClass().getResource("/icon/boton8.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(298, 298, 298))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiaIcono(int posicion){
        switch(posicion){
            case 0:
                jLabel1.setIcon(icon0);
                break;
            case 1:
                jLabel1.setIcon(icon1);
                break;
            case 2:
                jLabel1.setIcon(icon2);
                break;
            case 3:
                jLabel1.setIcon(icon3);
                break;
            case 4:
                jLabel1.setIcon(icon4);
                break;
            case 5:
                jLabel1.setIcon(icon5);
                break;
            case 6:
                jLabel1.setIcon(icon6);
                break;
            case 7:
                jLabel1.setIcon(icon7);
                break;
            case 8:
                jLabel1.setIcon(icon8);
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wheelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wheelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wheelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wheelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wheelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private int posicion;

    public int getPosicion() {
        return posicion;
    }

    public void setPosicion(int posicion) {
        this.posicion = posicion;
    }
    
    
}
